services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1308
      - POSTGRES_DB=mydb
      - POSTGRES_ROOT_PASSWORD=1308
